services:
  frontend:
    image: beidongjiedeguang/chatroom-frontend:ubunt2004
    ports:
      - "80:80"
    volumes:
      - ./web:/home
    depends_on:
      - backend
    container_name: frontend-container
    working_dir: /home
    command:
      - ./run-frontend.sh

  backend:
    image: beidongjiedeguang/chatroom-backend:ubunt2004
    ports:
      - "50052:50052"
    container_name: backend-container
#    networks:
#      back:
#        ipv4_address: 172.16.238.10
    depends_on:
      - grpc-proxy
    volumes:
      - .:/home
    working_dir: /home
    command:
      - ./run-backend.sh

  grpc-proxy:
    image: envoyproxy/envoy:v1.22.0
    ports:
      - "50050:50050"
    container_name: grpc-envoy-container
    volumes:
      - ./backend/envoy.yaml:/etc/envoy/envoy.yaml:ro
#    networks:
#      back:
#        ipv4_address: 172.16.238.11

#networks:
#  back:
#    name: network_for_chatroom
#    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: "172.16.238.0/24"